### ISSUE TITLE
How do I point this to ollama running on my localhost?

### ISSUE THREAD

**Issue by prasannaMAG** [SecureAI-Tools/SecureAI-Tools#104]
I set the MODEL_PROVIDER_CONFIG in the .env file to 
MODEL_PROVIDER_CONFIGS='[{"type":"OLLAMA","apiBaseUrl":"127.0.0.1:11434/","apiKey":"","options":{"numGpu":30}}]'
& have confirmed that the URL takes me to ollama's running server

How do I get it to use the ollama setup on my device. I have multiple models already downloaded & don't want a fresh download to happen everytime.

**Comment by nagug** [comment]
i made changes to the docker compose
INFERENCE_SERVER=http://host.docker.internal:11434/

also added extra host
```
 extra_hosts:
     - host.docker.internal:127.0.0.1
```
The machine is linux, hence the IP. 

I tried curling ollama directly. It all works

Following error, when i try to set the model in the model settings page.

```
TypeError: Failed to parse URL from 127.0.0.1:11434/api/generate
web-1                  |     at new Request (node:internal/deps/undici/undici:5272:19)
web-1                  |     at i (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:174332)
web-1                  |     ... 5 lines matching cause stack trace ...
web-1                  |     at s.startActiveSpan (/app/apps/web/.next/server/chunks/9369.js:1:16803)
web-1                  |     at a.startActiveSpan (/app/apps/web/.next/server/chunks/9369.js:1:17337)
web-1                  |     at /app/apps/web/.next/server/chunks/9369.js:1:47019 {
web-1                  |   [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
web-1                  |       at new NodeError (node:internal/errors:405:5)
web-1                  |       at new URL (node:internal/url:676:13)
web-1                  |       at new Request (node:internal/deps/undici/undici:5270:25)
web-1                  |       at i (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:174332)
web-1                  |       at U (/app/apps/web/.next/server/chunks/9369.js:1:39495)
web-1                  |       at /app/apps/web/.next/server/chunks/9369.js:1:41608
web-1                  |       at /app/apps/web/.next/server/chunks/9369.js:1:47167
web-1                  |       at a.with (/app/apps/web/.next/server/chunks/9369.js:1:7548)
web-1                  |       at s.with (/app/apps/web/.next/server/chunks/9369.js:1:1748)
web-1                  |       at s.startActiveSpan (/app/apps/web/.next/server/chunks/9369.js:1:16803) {
web-1                  |     input: '127.0.0.1:11434/api/generate',
web-1                  |     code: 'ERR_INVALID_URL'
web-1                  |   }
```

**Comment by nodecentral** [comment]
Hi, Any updates on this error ?

**Comment by acanthusian** [comment]
Here's how I was able to run this on a Mac with Ollama running locally. It's currently ingesting PDFs through paperless-ngx and the performance is much much faster with GPU support.

1. Find out local network interface IP (i.e. 192.168.0.101)
2. Modify docker-compose.yml so all values for INFERENCE_SERVER values point to your local IP (INFERENCE_SERVER=http://192.168.0.101:11434/)
3. Comment out the "inference" container at the bottom of the docker-compose.yml to avoid loading the Ollama container.
4. In one terminal window, run the following commands to start Ollama so it's available your local network interface. You can also use 0.0.0.0 instead of your IP to make Ollama listen on all interfaces.
`export OLLAMA_HOST=192.168.0.101`
`ollama serve`
5. In another terminal window, spin up the stack with `docker-compose up`
