### ISSUE TITLE
Taskmanager fatal error Channel closed by server: 406

### ISSUE THREAD

**Issue by Saboral** [SecureAI-Tools/SecureAI-Tools#106]
Trying to process document, continually getting error in task manager log, taskmanager process drops. Resumes upon restarting taskmanager.

`2024-05-06 18:14:46 [info]: [doc = HDyfuMOHElt0fLrieExhj] chunk -> {"service":"model-provider-service","status":"Processing chunk 4201 of 4382"}
node:events:495
      throw er; // Unhandled 'error' event
      ^
Error: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more"
    at C.accept (/app/node_modules/amqplib/lib/channel.js:421:17)
    at Connection.mainAccept [as accept] (/app/node_modules/amqplib/lib/connection.js:63:33)
    at Socket.go (/app/node_modules/amqplib/lib/connection.js:486:48)
    at Socket.emit (node:events:517:28)
    at emitReadable_ (node:internal/streams/readable:633:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
Emitted 'error' event on ChannelModel instance at:
    at Connection.emit (node:events:517:28)
    at C.onSocketError (/app/node_modules/amqplib/lib/connection.js:361:10)
    at Connection.emit `(node:events:517:28)`
    at Socket.go (/app/node_modules/amqplib/lib/connection.js:489:12)
    at Socket.emit (node:events:517:28)
    at emitReadable_ (node:internal/streams/readable:633:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {

  code: 406,
  classId: 0,
  methodId: 0
}
Node.js v18.19.0`

**Comment by Saboral** [comment]
Realized this was a duplicate of a previous issue. Note that rabbitmq used in this repo does not except the modern configs. The 10-defaults file in the docker must be updated with consumer_handshake = [a large number] to fix.
