### ISSUE TITLE
Document Collection never processes documents

### ISSUE THREAD

**Issue by DaelonSuzuka** [SecureAI-Tools/SecureAI-Tools#50]
When I create a new Document Collection and upload pdfs to it, it says that it's processing the documents in the background, but it's not.

The same document processes successfully if I create a new chat and upload it that way.

**Comment by JayNakrani** [comment]
Oh, interesting. Can you please post the logs from `task-master`, `web`, and `message-broker` containers? The `task-master` container should be processing documents in the background -- looking at all three container logs will give us an insight into what's going wrong.

**Comment by DaelonSuzuka** [comment]
Sorry for the delay, I'll try to get that log output today.

**Comment by mrgaalgdornick** [comment]
[_secure-ai-tools-message-broker-1_logs.txt](https://github.com/SecureAI-Tools/SecureAI-Tools/files/13726413/_secure-ai-tools-message-broker-1_logs.txt)
[_secure-ai-tools-task-master-1_logs.txt](https://github.com/SecureAI-Tools/SecureAI-Tools/files/13726414/_secure-ai-tools-task-master-1_logs.txt)
[_secure-ai-tools-web-1_logs.txt](https://github.com/SecureAI-Tools/SecureAI-Tools/files/13726415/_secure-ai-tools-web-1_logs.txt)
![containers status](https://github.com/SecureAI-Tools/SecureAI-Tools/assets/104127886/daa01ab1-d837-4aae-8114-71043a8154cc)
Same here.
But in my case, in a new chat, the document is not processed either.
In Docker the task-master is not running. When I start it, its stops running after a while.

I will send you the log files.

**Comment by JayNakrani** [comment]
@mrgaalgdornick Thank you for the detailed logs.

From task-master logs, 
> file:///app/node_modules/langchain/dist/embeddings/ollama.js:97
>             throw new Error(`Request to Ollama server failed: ${response.status} ${response.statusText}`);
>                   ^
> Error: Request to Ollama server failed: 404 Not Found
>     at OllamaEmbeddings._request (file:///app/node_modules/langchain/dist/embeddings/ollama.js:97:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async RetryOperation._fn (/app/node_modules/p-retry/index.js:50:12) {
>   attemptNumber: 7,
>   retriesLeft: 0
> }

Looks like either Ollama (inference) isn't running, or perhaps that the model wasn't downloaded prior to submitting documents. Can you please confirm if you downloaded the model ([step 6.2 here on how to download the model](https://github.com/SecureAI-Tools/SecureAI-Tools?tab=readme-ov-file#6-post-installation-set-up))?

**Comment by mrgaalgdornick** [comment]
> @mrgaalgdornick Thank you for the detailed logs.
> 
> Looks like either Ollama (inference) isn't running, or perhaps that the model wasn't downloaded prior to submitting documents. Can you please confirm if you downloaded the model ([step 6.2 here on how to download the model](https://github.com/SecureAI-Tools/SecureAI-Tools?tab=readme-ov-file#6-post-installation-set-up))?

Thanks for your response.
In my enthusiasm, I apparently skipped this step. 
Now that the model has been downloaded, unfortunately, it still doesn't work. Here are the new logs. 

I have opted for the basic installation without OpenAI LLMs or GPU support (I am running on Windows 10). From the logging it seems that MODEL_PROVIDER_CONFIGS still needs to be set? But to what if not using OpenAI LLMs?

[_secure-ai-tools-message-broker-1_logs.txt](https://github.com/SecureAI-Tools/SecureAI-Tools/files/13737629/_secure-ai-tools-message-broker-1_logs.txt)
[_secure-ai-tools-task-master-1_logs.txt](https://github.com/SecureAI-Tools/SecureAI-Tools/files/13737630/_secure-ai-tools-task-master-1_logs.txt)
[_secure-ai-tools-web-1_logs.txt](https://github.com/SecureAI-Tools/SecureAI-Tools/files/13737631/_secure-ai-tools-web-1_logs.txt)

**Comment by eyalspier** [comment]
+1 - same issue for me!

**Comment by mpr1255** [comment]
I _thought_ I had the same issue, but it's actually just because it's extremely slow. Is the embedding not implemented with async? Is it a network or skill or other issue on my end? I have docker resources turned up pretty high. I downgraded it from large embedding model to small (using openai). But it seems the chunks are simply being processed sequentially, and so it is always going to be massively bottlenecked. I would have thought we should have 10 threads running simultaneously with some backoff decorators or something? The throughput is not going to work for thousands documents, let alone tens of thousands. Even a test pile of 200 docs is taking forever.
