### ISSUE TITLE
error on upload doc

### ISSUE THREAD

**Issue by KingPin** [SecureAI-Tools/SecureAI-Tools#57]
using docker-compose from GitHub repo everything loads fine but when I try to upload docs I get the following error in the console:

```
web                  |  ⨯ Error: TypeError: fetch failed
web                  |     at F.createCollection (/app/apps/web/.next/server/chunks/1820.js:47:35772)
web                  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web                  |     at async f (/app/apps/web/.next/server/app/api/organizations/[orgIdOrSlug]/document-collections/route.js:1:2103)
web                  |     at async /app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:41960
web                  |  ⨯ Error: TypeError: fetch failed
web                  |     at F.createCollection (/app/apps/web/.next/server/chunks/1820.js:47:35772)
web                  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web                  |     at async f (/app/apps/web/.next/server/app/api/organizations/[orgIdOrSlug]/document-collections/route.js:1:2103)
web                  |     at async /app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:41960
```

and the following error shows up in the top right corner of the webUI:

`Something went wrong. Please try again later.`

**Comment by JayNakrani** [comment]
Oh, interesting. This probably means that vector-db isn't running. Can you post logs from the vector-db container?

**Comment by KingPin** [comment]
```
sait-vector-db  | Rebuilding hnsw to ensure architecture compatibility
sait-vector-db  | Collecting chroma-hnswlib
sait-vector-db  |   Downloading chroma_hnswlib-0.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
sait-vector-db  |      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 12.0 MB/s eta 0:00:00
sait-vector-db  | Collecting numpy
sait-vector-db  |   Downloading numpy-1.26.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
sait-vector-db  |      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 35.6 MB/s eta 0:00:00
sait-vector-db  | Installing collected packages: numpy, chroma-hnswlib
sait-vector-db  |   Attempting uninstall: numpy
sait-vector-db  |     Found existing installation: numpy 1.26.2
sait-vector-db  |     Uninstalling numpy-1.26.2:
sait-vector-db  |       Successfully uninstalled numpy-1.26.2
sait-vector-db  |   Attempting uninstall: chroma-hnswlib
sait-vector-db  |     Found existing installation: chroma-hnswlib 0.7.3
sait-vector-db  |     Uninstalling chroma-hnswlib-0.7.3:
sait-vector-db  |       Successfully uninstalled chroma-hnswlib-0.7.3
sait-vector-db  | Successfully installed chroma-hnswlib-0.7.3 numpy-1.26.2
sait-vector-db  | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
sait-vector-db  |
sait-vector-db  | [notice] A new release of pip is available: 23.0.1 -> 23.3.2
sait-vector-db  | [notice] To update, run: pip install --upgrade pip
sait-vector-db  | /chroma/./chromadb/utils/embedding_functions.py:584: SyntaxWarning: "is" with a literal. Did you mean "=="?
sait-vector-db  |   if self._task_type is "RETRIEVAL_DOCUMENT":
sait-vector-db  | DEBUG:    [18-12-2023 23:45:44] Registering provider: token_config
sait-vector-db  | DEBUG:    [18-12-2023 23:45:44] Registering provider: user_token_config
sait-vector-db  | DEBUG:    [18-12-2023 23:45:44] Registering provider: token
sait-vector-db  | DEBUG:    [18-12-2023 23:45:44] Registering provider: token
sait-vector-db  | WARNING:  [18-12-2023 23:45:45] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048576. chroma_server_nofile will not be set.
sait-vector-db  | INFO:     [18-12-2023 23:45:45] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
sait-vector-db  | DEBUG:    [18-12-2023 23:45:45] Starting component System
sait-vector-db  | DEBUG:    [18-12-2023 23:45:45] Starting component OpenTelemetryClient
sait-vector-db  | DEBUG:    [18-12-2023 23:45:45] Starting component SimpleAssignmentPolicy
sait-vector-db  | DEBUG:    [18-12-2023 23:45:45] Starting component SqliteDB
sait-vector-db  | DEBUG:    [18-12-2023 23:45:45] Starting component Posthog
sait-vector-db  | DEBUG:    [18-12-2023 23:45:45] Starting component LocalSegmentManager
sait-vector-db  | DEBUG:    [18-12-2023 23:45:45] Starting component SegmentAPI
sait-vector-db  | INFO:     [18-12-2023 23:45:45] Started server process [11]
sait-vector-db  | INFO:     [18-12-2023 23:45:45] Waiting for application startup.
sait-vector-db  | INFO:     [18-12-2023 23:45:45] Application startup complete.
sait-vector-db  | INFO:     [18-12-2023 23:45:45] Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
```

**Comment by JayNakrani** [comment]
Huh, that's weird. The vector-db doesn't have any errors. So I suspect that this may have been a temporary issue where web service couldn't reach vector-db. Can you try again and if you run into this error can you post logs from both web and vector-db containers?

**Comment by KingPin** [comment]
The log I posted was from a fresh run where I tried uploading a file and got the error. But I will do another run in the morning and post both logs.

**Comment by KingPin** [comment]
only real error I noticed was in the taskmaster logs : 

```
sait-task-master          | (node:1) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
sait-task-master          | (Use `node --trace-warnings ...` to show where the warning was created)
sait-task-master          | LOG_DIR = /app/volume/logs/
sait-task-master          | 2023-12-18 23:45:40 [info]: Starting task-master... -> {"service":"model-provider-service"}
sait-task-master          | node:internal/process/promises:288
sait-task-master          |             triggerUncaughtException(err, true /* fromPromise */);
sait-task-master          |             ^
sait-task-master          |
sait-task-master          | Error: connect ECONNREFUSED 172.24.0.2:5672
sait-task-master          |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
sait-task-master          |   errno: -111,
sait-task-master          |   code: 'ECONNREFUSED',
sait-task-master          |   syscall: 'connect',
sait-task-master          |   address: '172.24.0.2',
sait-task-master          |   port: 5672
sait-task-master          | }
sait-task-master          |
sait-task-master          | Node.js v18.19.0
```
the rabbitmq connection string is the same on the web container, and it doesnt throw any errors about the connection, I will test that further also.
I will look at cleaning up and posting other logs later.

**Comment by JayNakrani** [comment]
I think this task-master error probably means that the message-broker wasn't ready when the task-master tried to connect to it. Maybe it took a while for message-broker to start

**Comment by JayNakrani** [comment]
@KingPin We have added the health checks in the latest version -- [v0.0.3](https://github.com/SecureAI-Tools/SecureAI-Tools/releases/tag/v0.0.3) to solve these issues. Please try it out and let me know if you run into any issues.
