### ISSUE TITLE
Error: ids, embeddings, metadatas, and documents must all be the same length

### ISSUE THREAD

**Issue by AhmadMuj** [SecureAI-Tools/SecureAI-Tools#59]
Hello
First of all, thank you for the great work.
I have encountered an issue with the task-master where it will run before the messages broker, I have solved the issue temporarily by adding a sleep of 10 before run command 
```
command: sh -c "sleep 30 && 
```
The problem now is that after I upload some PDF files to a documents collection, I'm getting this error from the task-master
```
file:///app/node_modules/chromadb/dist/chromadb.mjs:1293
      throw new Error(
            ^

Error: ids, embeddings, metadatas, and documents must all be the same length
    at Collection.validate (file:///app/node_modules/chromadb/dist/chromadb.mjs:1293:13)
    at Collection.add (file:///app/node_modules/chromadb/dist/chromadb.mjs:1331:84)
    at IndexingService.index (file:///app/packages/backend/dist/services/indexing-service.js:67:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async channel.consume.noAck (file:///app/apps/task-master/dist/main.js:24:30)

Node.js v18.19.0
```
Thank you in advance

**Comment by AhmadMuj** [comment]
The problem was gone when I changed the PDF files. So I think it's something related to one of the PDFs that I was uploading. 
I uploaded documents with variable sizes ( between 6 to 50 pages ) so maybe that's the reason.
Anyways, it would be better to ignore the PDF that is causing the issue and continue the processing of the other documents. 
Also once a document collection processing fails, it will never try to process them again

**Comment by JayNakrani** [comment]
> I have encountered an issue with the task-master where it will run before the messages broker, I have solved the issue temporarily by adding a sleep of 10 before run command

Oh, interesting. We should probably add a health check to docker-compose so that the task-master only starts after the message-broker is healthy.

> Error: ids, embeddings, metadatas, and documents must all be the same length

This error is coming from [here](https://github.com/SecureAI-Tools/SecureAI-Tools/blob/35e9acb2b5d4b63f1c0e21c607173498ed6e89da/packages/backend/src/services/indexing-service.ts#L87l-L92) where it's processing one PDF. It is complaining that all of the arrays (ids, embeddings, metadatas etc) aren't of same length. I think it's because maybe some embedding calls failed or something else went wrong.

Can you share full logs of task-master and inference containers? May be it would give us a clue

**Comment by JayNakrani** [comment]
Re: health check

Can you please try docker-compose file at https://github.com/SecureAI-Tools/SecureAI-Tools/blob/jay/db-health-check/deployment/docker-compose.yml ? I added health check for message-broker and db both services.

**Comment by ArjenR** [comment]
I had error when I did a fresh install. Chat history would not load and I got an error when accessing the Document Collections page. I noticed that the db-migrate-and-seed errored out on first run.  I adopted these changes and now things work well again. 

For anyone reading this later. Also **really** clear out the cookies and site settings for your secure-ai site when you start new.

**Comment by JayNakrani** [comment]
> Error: ids, embeddings, metadatas, and documents must all be the same length

I found the root cause of this error. It happens when PDFLoader can't read any text from the document. I've pushed a fix to ignore such documents and move on. It will get released in the next version
