### ISSUE TITLE
[next-auth][error][NO_SECRET]

### ISSUE THREAD

**Issue by europacafe** [SecureAI-Tools/SecureAI-Tools#69]
just wipe out my 0.0.2 and install v0.0.3 from scratch. I can't login with the default bruce@.... 
```
[next-auth][error][NO_SECRET] 
https://next-auth.js.org/errors#no_secret Please define a `secret` in production. MissingSecret [MissingSecretError]: Please define a `secret` in production.
    at assertConfig (/app/node_modules/next-auth/core/lib/assert.js:42:12)
    at AuthHandler (/app/node_modules/next-auth/core/index.js:77:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextAuthApiHandler (/app/node_modules/next-auth/next/index.js:22:19)
    at async NextAuth._args$ (/app/node_modules/next-auth/next/index.js:108:14) {
  code: 'NO_SECRET'
}
```

**Comment by JayNakrani** [comment]
Can you check the value of `NEXTAUTH_SECRET` in `.env` file? The default set-up script should have put randomly generated secret there -- but may be it wasn't run or didn't succeed?

**Comment by europacafe** [comment]
NEXTAUTH_SECRET has the generated value.
ec66cc8c4de40221250a...........a86884a752b858985
When I spin up with docker compose up -d
![image](https://github.com/SecureAI-Tools/SecureAI-Tools/assets/51871976/0d1a1953-705b-47ba-9c86-75a19a78a766)

When I look at the database migrate log:
`sh: can't open 'apps/web/tools/db-migrate-and-seed.sh': No such file or directory`
