### ISSUE TITLE
Ollama call failed with status code 404: model 'mistral' not found

### ISSUE THREAD

**Issue by BloodBlight** [SecureAI-Tools/SecureAI-Tools#8]
Looks like maybe a URL changed and it can't pull the model for new install?  Maybe a permissions issue?  Seems like all of the files (listed below) are all running as root.

Web Server:
```
Error: Ollama call failed with status code 404: model 'mistral' not found, try pulling it first
    at createOllamaStream (/app/.next/server/chunks/8624.js:2204:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatOllama._streamResponseChunks (/app/.next/server/chunks/8624.js:2528:26)
    at async ChatOllama._call (/app/.next/server/chunks/8624.js:2577:26)
    at async ChatOllama._generate (/app/.next/server/chunks/8624.js:6663:22)
    at async Promise.allSettled (index 0)
    at async ChatOllama.generate (/app/.next/server/chunks/8624.js:6556:25)
    at async ChatOllama.call (/app/.next/server/chunks/8624.js:6619:24) {
  response: _Response [Response] {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 404,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Not Found',
      headersList: [_HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: _HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}
```

Inference:
```
[GIN] 2023/12/01 - 03:07:12 | 404 |     169.253µs |      172.21.0.3 | POST     "/api/generate"
```

Current file structure looks like:
```
/DFS/Docker-HDD/SecureAI-Tools/
/DFS/Docker-HDD/SecureAI-Tools/Web
/DFS/Docker-HDD/SecureAI-Tools/Web/logs
/DFS/Docker-HDD/SecureAI-Tools/Web/logs/logs
/DFS/Docker-HDD/SecureAI-Tools/Web/logs/logs/.9564a7becd16e300bf8acb38f8e5244756442805-audit.json
/DFS/Docker-HDD/SecureAI-Tools/Web/logs/logs/secure-ai-tools-2023-12-01.log
/DFS/Docker-HDD/SecureAI-Tools/Web/data
/DFS/Docker-HDD/SecureAI-Tools/Web/data/SecureAI-Tools.db
/DFS/Docker-HDD/SecureAI-Tools/inference-ollama
/DFS/Docker-HDD/SecureAI-Tools/inference-ollama/id_ed25519.pub
/DFS/Docker-HDD/SecureAI-Tools/inference-ollama/id_ed25519
/DFS/Docker-HDD/SecureAI-Tools/inference-ollama/models
/DFS/Docker-HDD/SecureAI-Tools/inference-ollama/models/blobs
```

**Comment by JayNakrani** [comment]
Did you download the model first? It's the step 6.2 at https://github.com/SecureAI-Tools/SecureAI-Tools#6-post-installation-set-up

If it happens even after that then it's definitely weird

**Comment by BloodBlight** [comment]
😣😖😱  Um, no....  Thank you..
