### ISSUE TITLE
Timeout when procession documents 

### ISSUE THREAD

**Issue by tarek369** [SecureAI-Tools/SecureAI-Tools#80]
I get this error when Processing document, how can I increase the timeout ?

`node:events:495
      throw er; // Unhandled 'error' event
      ^
Error: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more"
    at C.accept (/app/node_modules/amqplib/lib/channel.js:421:17)
    at Connection.mainAccept [as accept] (/app/node_modules/amqplib/lib/connection.js:63:33)
    at Socket.go (/app/node_modules/amqplib/lib/connection.js:486:48)
    at Socket.emit (node:events:517:28)
    at emitReadable_ (node:internal/streams/readable:633:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
Emitted 'error' event on ChannelModel instance at:
    at Connection.emit (node:events:517:28)
    at C.onSocketError (/app/node_modules/amqplib/lib/connection.js:361:10)
    at Connection.emit (node:events:517:28)
    at Socket.go (/app/node_modules/amqplib/lib/connection.js:489:12)
    at Socket.emit (node:events:517:28)
    at emitReadable_ (node:internal/streams/readable:633:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {

  code: 406,
  classId: 0,
  methodId: 0
}
Node.js v18.19.0
`

**Comment by JayNakrani** [comment]
30 minutes is the default `consumer_timeout` in RabbitMQ.

It can be overridden by editing the `/etc/rabbitmq/rabbitmq.config` file inside RabbitMQ's docker container and restarting RabbitMQ. Alternatively, you can also create the file locally and mount it like https://stackoverflow.com/a/42003732 (this will also persist the config between docker runs)

**Comment by JayNakrani** [comment]
I am converting this into a discussion because it's better suited there
