### ISSUE TITLE
Portainer Error: Invalid AMQP_DOCS_INDEXING_QUEUE_NAME

### ISSUE THREAD

**Issue by K4HVH** [SecureAI-Tools/SecureAI-Tools#85]
Hello, 
I am trying to set up the environment using volumes instead of binds, however I recieve the following error in the task-master container.
`Error: Invalid AMQP_DOCS_INDEXING_QUEUE_NAME`

`Migrate-and-Seed` is exiting with **_code 0_** and `Task-Master` is exiting with _**code 1**_

Below is the compose I'm using, I have simply added volumes and removed the dependency for the .env file as I am deploying via Portainer and can set the variables there (I have imported the .env file to portainer and are using the defaults)

```version: "3.8"

services:
  web:
    image: public.ecr.aws/d8f2p0h3/secure-ai-tools:latest
    platform: linux/amd64
    volumes:
      - web:/app/volume
    environment:
      - INFERENCE_SERVER=http://inference:11434/
      - VECTOR_DB_SERVER=http://vector-db:8000
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - AMQP_SERVER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@message-broker:5672
    ports:
      - 28669:28669
    command: sh -c "cd /app && node apps/web/server.js"
    depends_on:
      db:
        condition: service_healthy
      inference:
        condition: service_started
      vector-db:
        condition: service_started
      message-broker:
        condition: service_healthy
      db-migrate-and-seed:
        condition: service_completed_successfully
        restart: false

  task-master:
    image: public.ecr.aws/d8f2p0h3/secure-ai-tools:latest
    platform: linux/amd64
    volumes:
      - web:/app/volume
    environment:
      - INFERENCE_SERVER=http://inference:11434/
      - VECTOR_DB_SERVER=http://vector-db:8000
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - AMQP_SERVER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@message-broker:5672
    command: sh -c "cd /app/apps/task-master/ && node --experimental-specifier-resolution=node dist/main.js"
    depends_on:
      db:
        condition: service_healthy
      inference:
        condition: service_started
      vector-db:
        condition: service_started
      message-broker:
        condition: service_healthy
      db-migrate-and-seed:
        condition: service_completed_successfully
        restart: false

  # Performs DB schema migrations and seeds db with initial data if needed.
  db-migrate-and-seed:
    image: public.ecr.aws/d8f2p0h3/secure-ai-tools:latest
    platform: linux/amd64
    volumes:
      - web:/app/volume
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: sh -c "cd /app && sh apps/web/tools/db-migrate-and-seed.sh ${DATABASE_FILE}"
    deploy:
      restart_policy:
        condition: none
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 8

  vector-db:
    image: chromadb/chroma:latest
    volumes:
      # Default configuration for persist_directory is "/chroma/chroma/"
      - vector-db:/chroma/chroma/

  message-broker:
    image: rabbitmq:management
    volumes:
      - message-broker:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 3s
      timeout: 3s
      retries: 30

  inference:
    image: ollama/ollama:latest
    volumes:
      - inference:/root/.ollama
    #
    # Uncomment for Linux machines with Nvidia GPUs
    # Based on https://docs.docker.com/compose/gpu-support/
    # Requires Nvidia container toolkit: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installation
    #
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 'all'
              capabilities: [gpu]

volumes:
  web:
  db:
  vector-db:
  message-broker:
  inference:
```

The full log from task-master is below:

```(node:1) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
(Use node --trace-warnings ... to show where the warning was created)
LOG_DIR = undefined
2024-01-09 23:46:26 [info]: Starting task-master... -> {"service":"model-provider-service"}
file:///app/apps/task-master/dist/main.js:13
        throw new Error("Invalid AMQP_DOCS_INDEXING_QUEUE_NAME");
              ^
Error: Invalid AMQP_DOCS_INDEXING_QUEUE_NAME
    at main (file:///app/apps/task-master/dist/main.js:13:15)
    at file:///app/apps/task-master/dist/main.js:40:1
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12)
Node.js v18.19.0
```

And just for reference, the environmental variable for `AMQP_DOCS_INDEXING_QUEUE_NAME` is still the default `"documents-indexing-queue"`

**Comment by JayNakrani** [comment]
> ... I am deploying via Portainer and can set the variables there
> ... just for reference, the environmental variable for AMQP_DOCS_INDEXING_QUEUE_NAME is still the default "documents-indexing-queue"

It's possible that in your set-up, the env var is not being passed to the task-master container or has some extra characters. I don't know much about portainer, but you can verify this by doing the following:

1. Change the `task-master`'s `command` to be `sh -c "sleep 100000"` [here](https://github.com/SecureAI-Tools/SecureAI-Tools/blob/c33c98ae83900952448083d67ec903b258cdb426/deployment/docker-compose.yml#L52).
2. Bring up the containers
3. Exec into the container: `docker exec -it <container-name> /bin/sh`
4. [inside the container] Run `echo $AMQP_DOCS_INDEXING_QUEUE_NAME` to print the name of env var exactly as is.

**Comment by K4HVH** [comment]
> It's possible that in your set-up, the env var is not being passed to the task-master container or has some extra characters. I don't know much about portainer, but you can verify this by doing the following:

Thanks for the response, After looking into it it appears to be an ongoing issue with portainer. Environmental Variables are not getting set correctly inside of the containers. 

After running the command to print them out, they would just be left as `""` (blanks). The work-around I have done to get it working for now is to manually add the environmental variable in the *environment* section as below:

```  task-master:
    image: public.ecr.aws/d8f2p0h3/secure-ai-tools:latest
    platform: linux/amd64
    volumes:
      - web:/app/volume
    environment:
      - INFERENCE_SERVER=http://inference:11434/
      - VECTOR_DB_SERVER=http://vector-db:8000
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - AMQP_SERVER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@message-broker:5672
      - AMQP_DOCS_INDEXING_QUEUE_NAME=${AMQP_DOCS_INDEXING_QUEUE_NAME}
```

**Comment by K4HVH** [comment]
After reviewing I found the real issue. Portainer uses a different naming scheme when trying to reference ENV VARs inside the containers.

The fix is simply changing 
```    
  env_file:
      - .env
```
to 
```    
  env_file:
      - stack.env
```
in every service.

This allows for the variables to be passed into the container. Maybe add this into the documentation somewhere so other people with similar setups don't have this problem @JayNakrani
