### ISSUE TITLE
Can't process documents

### ISSUE THREAD

**Issue by Vaseemes** [SecureAI-Tools/SecureAI-Tools#86]
Hi,

My setup:

Running LM Studio on my Windows VM. And running SecureAI-Tools in a docker on my Ubuntu VM.

Issue:
I managed to connect these two and chat is working perfectly. But when I try to upload any PDF (long or one-pager), I instantly get this error in LM Studio: `[ERROR] Unexpected endpoint or method. (POST /v1/embeddings). Returning 200 anyway
`
And in the SecureAI-Tools I get this:
```
 ⨯ Error: failed to pipe response
    at pipeToNodeResponse (/app/node_modules/next/dist/server/pipe-readable.js:111:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendResponse (/app/node_modules/next/dist/server/send-response.js:40:13)
    at async doRender (/app/node_modules/next/dist/server/base-server.js:1360:25)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/next/dist/server/base-server.js:1552:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/next/dist/server/base-server.js:1460:28)
    at async NextNodeServer.renderPageComponent (/app/node_modules/next/dist/server/base-server.js:1843:24)
    at async NextNodeServer.renderToResponseImpl (/app/node_modules/next/dist/server/base-server.js:1881:32)
    at async NextNodeServer.pipeImpl (/app/node_modules/next/dist/server/base-server.js:909:25)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:266:17) {
  [cause]: TypeError: Cannot read properties of undefined (reading '0')
      at l.embedDocuments (/app/apps/web/.next/server/chunks/1820.js:57:5988)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async X.indexNewDocument (/app/apps/web/.next/server/chunks/4013.js:1:13173)
      at async X.index (/app/apps/web/.next/server/chunks/4013.js:1:12328)
      at async Object.pull (/app/apps/web/.next/server/app/api/document-collections/[documentCollectionId]/documents/[documentId]/index/route.js:2:66)
```

There are no other errors in any other containers. And in the GUI it just says that it's Processing documents but nothing is really happening.

**Comment by JayNakrani** [comment]
Thanks for the detailed report. 

> [ERROR] Unexpected endpoint or method. (POST /v1/embeddings). Returning 200 anyway

The error above probably means that LM-Studio doesn't support OpenAI-compatible REST API. SecureAI-Tools expects the LLM-runner to either have an Ollama-compatible or OpenAI-compatible API.

**Comment by Vaseemes** [comment]
Thank you for your prompt reply. I changed to oobabooga as an OpenAI-compatible API provider and it's working now.
